version: "3.9"

services:
  dev:
    build: .
    container_name: amazonlinux-dev
    working_dir: /workspace
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace              # all repos auto-sync into container
      # - ~/.aws:/root/.aws         # AWS credentials
